import { PersonEntity } from "./person-entity.model";

export const MOCK_PEROPLE_REPO: PersonEntity[] = [
    {
        "id": 1,
        "firstName": "Emmalee",
        "lastName": "Cullabine",
        "streetName": "Holmberg",
        "houseNumber": "92803",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Dungloe",
        "phoneNumber": "544-223-6560",
        "dateOfBirth": new Date("2006-12-06"),
    }, {
        "id": 2,
        "firstName": "Gib",
        "lastName": "Privost",
        "streetName": "Autumn Leaf",
        "houseNumber": "29",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Santa María de Caparo",
        "phoneNumber": "264-900-1351",
        "dateOfBirth": new Date("1998-03-21"),
    }, {
        "id": 3,
        "firstName": "Xavier",
        "lastName": "Birtley",
        "streetName": "Fulton",
        "houseNumber": "785",
        "apartmentNumber": "57577",
        "postalCode": "6600",
        "town": "Koper",
        "phoneNumber": "587-844-4626",
        "dateOfBirth": new Date("2021-07-06"),
    }, {
        "id": 4,
        "firstName": "Sheree",
        "lastName": "McVeighty",
        "streetName": "Grasskamp",
        "houseNumber": "0544",
        "apartmentNumber": null,
        "postalCode": "8045",
        "town": "Melbourne",
        "phoneNumber": "571-482-3732",
        "dateOfBirth": new Date("2001-11-02"),
    }, {
        "id": 5,
        "firstName": "Noelyn",
        "lastName": "Le Floch",
        "streetName": "Butterfield",
        "houseNumber": "561",
        "apartmentNumber": "68087",
        "postalCode": "Y21",
        "town": "Jiuxian",
        "phoneNumber": "721-979-6539",
        "dateOfBirth": new Date("1995-10-03"),
    }, {
        "id": 6,
        "firstName": "Jeniece",
        "lastName": "Crayk",
        "streetName": "Mccormick",
        "houseNumber": "7910",
        "apartmentNumber": null,
        "postalCode": "83120",
        "town": "Ban Ratsada",
        "phoneNumber": "739-917-6728",
        "dateOfBirth": new Date("2003-09-05"),
    }, {
        "id": 7,
        "firstName": "Tamqrah",
        "lastName": "Messruther",
        "streetName": "Doe Crossing",
        "houseNumber": "39626",
        "apartmentNumber": "3683",
        "postalCode": "95234",
        "town": "Soisy-sous-Montmorency",
        "phoneNumber": "275-888-6512",
        "dateOfBirth": new Date("1986-07-27"),
    }, {
        "id": 8,
        "firstName": "Normand",
        "lastName": "Shutle",
        "streetName": "Talmadge",
        "houseNumber": "041",
        "apartmentNumber": null,
        "postalCode": "8970",
        "town": "Kotel",
        "phoneNumber": "998-998-8804",
        "dateOfBirth": new Date("2001-03-15"),
    }, {
        "id": 9,
        "firstName": "Brook",
        "lastName": "Marnane",
        "streetName": "Fairview",
        "houseNumber": "31097",
        "apartmentNumber": "51",
        "postalCode": "2705-085",
        "town": "Azenhas do Mar",
        "phoneNumber": "890-524-3196",
        "dateOfBirth": new Date("1972-07-19"),
    }, {
        "id": 10,
        "firstName": "Janessa",
        "lastName": "De Filippi",
        "streetName": "Sunnyside",
        "houseNumber": "6606",
        "apartmentNumber": "5",
        "postalCode": "68213",
        "town": "El Calvario",
        "phoneNumber": "348-813-4010",
        "dateOfBirth": new Date("2007-05-01"),
    }, {
        "id": 11,
        "firstName": "Darda",
        "lastName": "Allworthy",
        "streetName": "Prairie Rose",
        "houseNumber": "582",
        "apartmentNumber": null,
        "postalCode": "2905",
        "town": "Tabug",
        "phoneNumber": "840-558-2643",
        "dateOfBirth": new Date("2003-01-06"),
    }, {
        "id": 12,
        "firstName": "Cati",
        "lastName": "Ruppele",
        "streetName": "Merry",
        "houseNumber": "991",
        "apartmentNumber": "93070",
        "postalCode": "2327",
        "town": "Rače",
        "phoneNumber": "209-943-5025",
        "dateOfBirth": new Date("1999-07-25"),
    }, {
        "id": 13,
        "firstName": "Beverlie",
        "lastName": "Barsham",
        "streetName": "Crescent Oaks",
        "houseNumber": "117",
        "apartmentNumber": null,
        "postalCode": "2000-452",
        "town": "Alqueidão",
        "phoneNumber": "300-369-7685",
        "dateOfBirth": new Date("2008-09-28"),
    }, {
        "id": 14,
        "firstName": "Mercedes",
        "lastName": "Gomersal",
        "streetName": "Pine View",
        "houseNumber": "05194",
        "apartmentNumber": "68322",
        "postalCode": "Y21",
        "town": "Caidian",
        "phoneNumber": "477-256-9943",
        "dateOfBirth": new Date("1986-02-04"),
    }, {
        "id": 15,
        "firstName": "Melinda",
        "lastName": "Greene",
        "streetName": "Buena Vista",
        "houseNumber": "164",
        "apartmentNumber": null,
        "postalCode": "9407",
        "town": "Limbalod",
        "phoneNumber": "750-983-3554",
        "dateOfBirth": new Date("1976-06-10"),
    }, {
        "id": 16,
        "firstName": "Carlita",
        "lastName": "Possel",
        "streetName": "Grover",
        "houseNumber": "2",
        "apartmentNumber": "252",
        "postalCode": "Y21",
        "town": "Dadong’ao",
        "phoneNumber": "926-580-2049",
        "dateOfBirth": new Date("2006-10-03"),
    }, {
        "id": 17,
        "firstName": "Beck",
        "lastName": "Stranio",
        "streetName": "Waywood",
        "houseNumber": "40",
        "apartmentNumber": null,
        "postalCode": "357239",
        "town": "Nagutskoye",
        "phoneNumber": "420-666-0381",
        "dateOfBirth": new Date("1988-03-02"),
    }, {
        "id": 18,
        "firstName": "Maud",
        "lastName": "Poxson",
        "streetName": "Melvin",
        "houseNumber": "7106",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Ballsh",
        "phoneNumber": "129-281-7260",
        "dateOfBirth": new Date("2011-09-14"),
    }, {
        "id": 19,
        "firstName": "Melisenda",
        "lastName": "Ligoe",
        "streetName": "Nobel",
        "houseNumber": "6",
        "apartmentNumber": null,
        "postalCode": "929-1174",
        "town": "Hamakita",
        "phoneNumber": "727-483-9273",
        "dateOfBirth": new Date("2003-09-10"),
    }, {
        "id": 20,
        "firstName": "Nannette",
        "lastName": "Dallimare",
        "streetName": "Northland",
        "houseNumber": "24",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Chibuto",
        "phoneNumber": "795-126-3364",
        "dateOfBirth": new Date("2013-10-28"),
    }, {
        "id": 21,
        "firstName": "Lin",
        "lastName": "Cicci",
        "streetName": "Rusk",
        "houseNumber": "9",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Pacanga",
        "phoneNumber": "569-264-1406",
        "dateOfBirth": new Date("1982-05-01"),
    }, {
        "id": 22,
        "firstName": "Jody",
        "lastName": "Bodker",
        "streetName": "Lillian",
        "houseNumber": "02",
        "apartmentNumber": "45",
        "postalCode": "98600",
        "town": "Mata-Utu",
        "phoneNumber": "665-308-6358",
        "dateOfBirth": new Date("1986-10-08"),
    }, {
        "id": 23,
        "firstName": "Rubetta",
        "lastName": "Camblin",
        "streetName": "Garrison",
        "houseNumber": "9546",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Laikit, Laikit II (Dimembe)",
        "phoneNumber": "604-770-2899",
        "dateOfBirth": new Date("2000-08-01"),
    }, {
        "id": 24,
        "firstName": "Josephina",
        "lastName": "Gibbonson",
        "streetName": "Michigan",
        "houseNumber": "404",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Pianbai",
        "phoneNumber": "320-223-5472",
        "dateOfBirth": new Date("1976-01-16"),
    }, {
        "id": 25,
        "firstName": "Trenna",
        "lastName": "Loadsman",
        "streetName": "Welch",
        "houseNumber": "4934",
        "apartmentNumber": "55",
        "postalCode": "Y21",
        "town": "Gegu",
        "phoneNumber": "920-763-7762",
        "dateOfBirth": new Date("1983-09-25"),
    }, {
        "id": 26,
        "firstName": "Marcelia",
        "lastName": "Hamlin",
        "streetName": "Twin Pines",
        "houseNumber": "6",
        "apartmentNumber": null,
        "postalCode": "97417",
        "town": "Saint-Denis",
        "phoneNumber": "931-353-9383",
        "dateOfBirth": new Date("1978-05-31"),
    }, {
        "id": 27,
        "firstName": "Jewel",
        "lastName": "Wearne",
        "streetName": "Sugar",
        "houseNumber": "8754",
        "apartmentNumber": null,
        "postalCode": "645 94",
        "town": "Strängnäs",
        "phoneNumber": "942-494-1974",
        "dateOfBirth": new Date("1970-05-19"),
    }, {
        "id": 28,
        "firstName": "Lonnard",
        "lastName": "Yaus",
        "streetName": "Manley",
        "houseNumber": "8",
        "apartmentNumber": "3",
        "postalCode": "Y21",
        "town": "San Ignacio",
        "phoneNumber": "603-473-1374",
        "dateOfBirth": new Date("1985-03-06"),
    }, {
        "id": 29,
        "firstName": "Forest",
        "lastName": "Jossel",
        "streetName": "Daystar",
        "houseNumber": "45185",
        "apartmentNumber": null,
        "postalCode": "6534",
        "town": "Labnig",
        "phoneNumber": "712-379-2317",
        "dateOfBirth": new Date("2013-09-25"),
    }, {
        "id": 30,
        "firstName": "Shepard",
        "lastName": "Kubas",
        "streetName": "Aberg",
        "houseNumber": "86",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Chahe",
        "phoneNumber": "280-370-8639",
        "dateOfBirth": new Date("2012-06-29"),
    }, {
        "id": 31,
        "firstName": "Tobe",
        "lastName": "Woodington",
        "streetName": "Texas",
        "houseNumber": "73",
        "apartmentNumber": null,
        "postalCode": "55150",
        "town": "Rāiwind",
        "phoneNumber": "243-430-0440",
        "dateOfBirth": new Date("2010-09-18"),
    }, {
        "id": 32,
        "firstName": "Aveline",
        "lastName": "Drabble",
        "streetName": "Maryland",
        "houseNumber": "0",
        "apartmentNumber": null,
        "postalCode": "42-293",
        "town": "Kalej",
        "phoneNumber": "787-723-5783",
        "dateOfBirth": new Date("1989-01-29"),
    }, {
        "id": 33,
        "firstName": "Rosemaria",
        "lastName": "Edlin",
        "streetName": "Monterey",
        "houseNumber": "426",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Kobuleti",
        "phoneNumber": "317-309-7765",
        "dateOfBirth": new Date("1992-02-09"),
    }, {
        "id": 34,
        "firstName": "Sheree",
        "lastName": "Leyrroyd",
        "streetName": "Northport",
        "houseNumber": "548",
        "apartmentNumber": null,
        "postalCode": "12001",
        "town": "San Marcos",
        "phoneNumber": "887-553-0904",
        "dateOfBirth": new Date("1993-11-30"),
    }, {
        "id": 35,
        "firstName": "Konrad",
        "lastName": "Kislingbury",
        "streetName": "Browning",
        "houseNumber": "0",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Robatal",
        "phoneNumber": "571-760-6573",
        "dateOfBirth": new Date("1975-11-11"),
    }, {
        "id": 36,
        "firstName": "Sal",
        "lastName": "McGoon",
        "streetName": "Bunker Hill",
        "houseNumber": "2799",
        "apartmentNumber": "24",
        "postalCode": "6000",
        "town": "Ankaran",
        "phoneNumber": "970-655-0983",
        "dateOfBirth": new Date("2019-06-10"),
    }, {
        "id": 37,
        "firstName": "Bernita",
        "lastName": "Ostick",
        "streetName": "Fordem",
        "houseNumber": "0",
        "apartmentNumber": "012",
        "postalCode": "056077",
        "town": "Betania",
        "phoneNumber": "426-640-1734",
        "dateOfBirth": new Date("1984-04-29"),
    }, {
        "id": 38,
        "firstName": "Peria",
        "lastName": "Riley",
        "streetName": "Milwaukee",
        "houseNumber": "9893",
        "apartmentNumber": null,
        "postalCode": "67144 CEDEX",
        "town": "Barr",
        "phoneNumber": "908-886-8754",
        "dateOfBirth": new Date("1971-05-27"),
    }, {
        "id": 39,
        "firstName": "Nissy",
        "lastName": "Beamiss",
        "streetName": "Nevada",
        "houseNumber": "76244",
        "apartmentNumber": null,
        "postalCode": "G6W",
        "town": "Québec",
        "phoneNumber": "347-719-3550",
        "dateOfBirth": new Date("2021-04-23"),
    }, {
        "id": 40,
        "firstName": "Dorian",
        "lastName": "Friedenbach",
        "streetName": "Annamark",
        "houseNumber": "83",
        "apartmentNumber": null,
        "postalCode": "624088",
        "town": "Kedrovoye",
        "phoneNumber": "721-240-5994",
        "dateOfBirth": new Date("2009-08-16"),
    }, {
        "id": 41,
        "firstName": "Reena",
        "lastName": "Abramof",
        "streetName": "Algoma",
        "houseNumber": "590",
        "apartmentNumber": null,
        "postalCode": "1109",
        "town": "Ani-e",
        "phoneNumber": "906-973-2690",
        "dateOfBirth": new Date("1990-06-06"),
    }, {
        "id": 42,
        "firstName": "Rozanna",
        "lastName": "Abramovitch",
        "streetName": "Mockingbird",
        "houseNumber": "0961",
        "apartmentNumber": "134",
        "postalCode": "Y21",
        "town": "Haoraoshan",
        "phoneNumber": "614-738-6551",
        "dateOfBirth": new Date("2022-07-05"),
    }, {
        "id": 43,
        "firstName": "Ira",
        "lastName": "Zeale",
        "streetName": "Thierer",
        "houseNumber": "90906",
        "apartmentNumber": null,
        "postalCode": "08-330",
        "town": "Kosów Lacki",
        "phoneNumber": "460-245-8776",
        "dateOfBirth": new Date("1979-02-05"),
    }, {
        "id": 44,
        "firstName": "Jennie",
        "lastName": "Galler",
        "streetName": "Holy Cross",
        "houseNumber": "60",
        "apartmentNumber": "7849",
        "postalCode": "1228",
        "town": "Желино",
        "phoneNumber": "641-912-2005",
        "dateOfBirth": new Date("2002-11-06"),
    }, {
        "id": 45,
        "firstName": "Shell",
        "lastName": "Rickis",
        "streetName": "Amoth",
        "houseNumber": "1",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Torbeck",
        "phoneNumber": "689-358-7786",
        "dateOfBirth": new Date("1999-02-17"),
    }, {
        "id": 46,
        "firstName": "Guillaume",
        "lastName": "Gabbett",
        "streetName": "Northport",
        "houseNumber": "9",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Taochuan",
        "phoneNumber": "250-472-7900",
        "dateOfBirth": new Date("2011-10-27"),
    }, {
        "id": 47,
        "firstName": "Shelagh",
        "lastName": "Durham",
        "streetName": "Thierer",
        "houseNumber": "74",
        "apartmentNumber": null,
        "postalCode": "4745-530",
        "town": "Fonteleite",
        "phoneNumber": "741-659-6807",
        "dateOfBirth": new Date("1995-02-21"),
    }, {
        "id": 48,
        "firstName": "Melicent",
        "lastName": "Agate",
        "streetName": "Merrick",
        "houseNumber": "2230",
        "apartmentNumber": null,
        "postalCode": "3517",
        "town": "Cabaritan East",
        "phoneNumber": "308-330-6373",
        "dateOfBirth": new Date("1980-09-28"),
    }, {
        "id": 49,
        "firstName": "Lanny",
        "lastName": "Moine",
        "streetName": "Mcguire",
        "houseNumber": "38988",
        "apartmentNumber": "9",
        "postalCode": "2601",
        "town": "La Trinidad",
        "phoneNumber": "420-797-5065",
        "dateOfBirth": new Date("1984-12-29"),
    }, {
        "id": 50,
        "firstName": "Christophorus",
        "lastName": "Whatling",
        "streetName": "Spenser",
        "houseNumber": "71",
        "apartmentNumber": null,
        "postalCode": "Y21",
        "town": "Gayamdesa",
        "phoneNumber": "607-424-0889",
        "dateOfBirth": new Date("1996-09-04"),
    },
];  